---
#CodeBook
--

##Quick description of how the data was proccessed (see README for more)

1) subject train and test data and combined into subjectAll
2) xtrain and xtest data combinde into xAll then paired down into just mean and std variables using features dataset
3) y test and y train and merged into yAll and labeled/named using activities dataset
4) joined subjectAll, xAll and yAll data frames into final
5. named data set with descriptive names and replaced abbreviations.

##Variables in new tidy dataset (modified from original)
---------
- subjectId: 1 to 30 each representing a participant in the study
- activity: the activity that the subject was doing at the time of the measurement
- tBodyacceleration-mean-X        
- tBodyacceleration-mean-Y
- tBodyacceleration-mean-Z
- tBodyacceleration-std-X
- tBodyacceleration-std-Y
- tBodyacceleration-std-Z
- tGravityacceleration-mean-X
- tGravityacceleration-mean-Y
- tGravityacceleration-mean-Z
- tGravityacceleration-std-X
- tGravityacceleration-std-Y
- tGravityacceleration-std-Z
- tBodyaccelerationJerk-mean-X
- tBodyaccelerationJerk-mean-Y
- tBodyaccelerationJerk-mean-Z
- tBodyaccelerationJerk-std-X
- tBodyaccelerationJerk-std-Y
- tBodyaccelerationJerk-std-Z
- tBodyGyro-mean-X
- tBodyGyro-mean-Y
- tBodyGyro-mean-Z
- tBodyGyro-std-X
- tBodyGyro-std-Y
- tBodyGyro-std-Z
- tBodyGyroJerk-mean-X
- tBodyGyroJerk-mean-Y
- tBodyGyroJerk-mean-Z
- tBodyGyroJerk-std-X
- tBodyGyroJerk-std-Y
- tBodyGyroJerk-std-Z
- tBodyaccelerationmagnitude-mean
- tBodyaccelerationmagnitude-std
- tGravityaccelerationmagnitude-mean
- tGravityaccelerationmagnitude-std
- tBodyaccelerationJerkmagnitude-mean
- tBodyaccelerationJerkmagnitude-std
- tBodyGyromagnitude-mean
- tBodyGyromagnitude-std
- tBodyGyroJerkmagnitude-mean
- tBodyGyroJerkmagnitude-std
- fBodyacceleration-mean-X
- fBodyacceleration-mean-Y
- fBodyacceleration-mean-Z
- fBodyacceleration-std-X
- fBodyacceleration-std-Y
- fBodyacceleration-std-Z
- fBodyaccelerationJerk-mean-X
- fBodyaccelerationJerk-mean-Y
- fBodyaccelerationJerk-mean-Z
- fBodyaccelerationJerk-std-X
- fBodyaccelerationJerk-std-Y
- fBodyaccelerationJerk-std-Z
- fBodyGyro-mean-X
- fBodyGyro-mean-Y
- fBodyGyro-mean-Z
- fBodyGyro-std-X
- fBodyGyro-std-Y
- fBodyGyro-std-Z
- fBodyaccelerationmagnitude-mean
- fBodyaccelerationmagnitude-std
- fBodyBodyaccelerationJerkmagnitude-mean
- fBodyBodyaccelerationJerkmagnitude-std
- fBodyBodyGyromagnitude-mean
- fBodyBodyGyromagnitude-std
- fBodyBodyGyroJerkmagnitude-mean
- fBodyBodyGyroJerkmagnitude-std

##About the Raw Data
The raw data was sourced from the UCI Machine Learning Repository and A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

This data consisted of 10299 smartphone sensor measurements split into two partitions, train and test several pieces (x, y, subject, features and activites)

Dataset x contained each observations measurements unnamed/labeled
Dataset y contained each observations activityID unnamed/labeled
Dataset subject contained each observations subject ID
Dataset features contained descriptive names of each measurement (eg. "tBodyAcceleration-mean()-X)
Dataset activities contained descriptive activity names (eg. SITTING, WALIKING)


##Information about original variables
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 

mean(): Mean value
std(): Standard deviation
mad(): Median absolute deviation 
max(): Largest value in array
min(): Smallest value in array
sma(): Signal magnitude area
energy(): Energy measure. Sum of the squares divided by the number of values. 
iqr(): Interquartile range 
entropy(): Signal entropy
arCoeff(): Autorregresion coefficients with Burg order equal to 4
correlation(): correlation coefficient between two signals
maxInds(): index of the frequency component with largest magnitude
meanFreq(): Weighted average of the frequency components to obtain a mean frequency
skewness(): skewness of the frequency domain signal 
kurtosis(): kurtosis of the frequency domain signal 
bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
tBodyAccMean
tBodyAccJerkMean
tBodyGyroMean
tBodyGyroJerkMean

The complete list of variables of each feature vector is available in 'features.txt'


